version: "3"
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER?:error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:error}
      POSTGRES_DB: ${POSTGRES_DB?:error}
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"
